from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^$', 'flame_speed.views.home', name='home'),  
                       url(r'^home/$', 'flame_speed.views.home', name='home'), 
                       url(r'^database/$', 'flame_speed.views.database', name='database'),
                       url(r'^characteristic/$', 'flame_speed.views.characteristic', name='characteristic'),
                       url(r'^reference/$', 'flame_speed.views.reference', name='reference'),
                       url(r'^mixture/$', 'flame_speed.views.mixture', name='mixture'),
                       url(r'^graph/$', 'flame_speed.views.graph', name='graph'),
                       url(r'^search/$', 'flame_speed.views.search', name='search'),
                       url(r'^Result_search/$', 'flame_speed.views.Result_search', name='Result_search'),  
                       url(r'^H2_air/$', 'flame_speed.views.H2_air', name='H2_air'),
                       url(r'^H2_air_steam/$', 'flame_speed.views.H2_air_steam', name='H2_air_steam'),
                       url(r'^H2_O2/$', 'flame_speed.views.H2_O2', name='H2_O2'),
                       url(r'^H2_CO/$', 'flame_speed.views.H2_CO', name='H2_CO'),
                       url(r'^H2_air_CO/$', 'flame_speed.views.H2_air_CO', name='H2_air_CO'),
                       url(r'^H2_air_CO2/$', 'flame_speed.views.H2_air_CO2', name='H2_air_CO2'),
                       url(r'^H2_air_CO_CO2/$', 'flame_speed.views.H2_air_CO_CO2', name='H2_air_CO_CO2'),
                       url(r'^H2_air_Pressure/$', 'flame_speed.views.H2_air_Pressure', name='H2_air_Pressure'),
                       url(r'^H2_air_Pressure_Ref1/$', 'flame_speed.views.H2_air_Pressure_Ref1', name='H2_air_Pressure_Ref1'),
                       url(r'^H2_air_CO_Pressure/$', 'flame_speed.views.H2_air_CO_Pressure', name='H2_air_Pressure'),
                       url(r'^H2_air_equivalence_ratio/$', 'flame_speed.views.H2_air_equivalence_ratio', name='H2_air_equivalence_ratio'),
                       url(r'^reference/populate_reference/$', 'flame_speed.views.populate_reference', name='populate_reference'),  
                       url(r'^characteristic/characteristic/$', 'flame_speed.views.characteristic', name='characteristic'), 
                       url(r'^mixture/populate_mixture_characteristic/$', 'flame_speed.views.populate_mixture_characteristic', name='populate_mixture_characteristic'),                                           
)
